drop database if exists GPLBANK;

create database GPLBANK;

use GPLBANK;

CREATE TABLE EMPLEADOS(
ID int AUTO_INCREMENT,
DNI varchar(9) UNIQUE,
PASS varchar(255),
COD_EMPLEADO varchar(255),
NOMBRE VARCHAR(255),
APELLIDO1 varchar(255),
APELLIDO2 varchar(255),
NOMBRE_JEFE varchar(255),
JEFE boolean,
DEPARTAMENTO varchar(255),
CLIENTES_CAPTADOS int,
PRODUCTOS_VENDIDOS int,
PRIMARY KEY (ID)
);

INSERT INTO EMPLEADOS (DNI, PASS, COD_EMPLEADO, JEFE) VALUES ('admin', '1000:13403c1902075346a9c787febc7b476de16abe5644f92139:692b2215cb3e526a11456f26a89944827a874b615af391bb', 'admin', 1);

CREATE TABLE CLIENTES(
DNI varchar(9),
PASS varchar(255),
NOMBRE varchar(255),
APELLIDO1 varchar(255),
APELLIDO2 varchar(255),
PRIMARY KEY (DNI)
);

CREATE TABLE TELEFONOS(
NUM_TELF varchar(255),
DNI varchar(255),
PRIMARY KEY (NUM_TELF),
FOREIGN KEY (DNI) REFERENCES CLIENTES (DNI) ON DELETE CASCADE
);

CREATE TABLE PRODUCTOS (
ID integer AUTO_INCREMENT,
TITULAR VARCHAR (255),
IMPORTE double,
TIPO integer NOT NULL,
DNI_CLIENTE VARCHAR(255) NOT NULL,

PRIMARY KEY (ID),
FOREIGN KEY (DNI_CLIENTE) REFERENCES CLIENTES (DNI) ON DELETE CASCADE    
);

CREATE TABLE TARJETAS (
ID integer AUTO_INCREMENT,
ID_PRODUCTO integer,
NUMERO_TARJETA varchar(255),
CADUCIDAD varchar(255),
ACTIVADA boolean,
PIN varchar(4),

PRIMARY KEY (ID),
FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS (ID) ON DELETE CASCADE
);

CREATE TABLE CUENTAS_NOMINA(
ID integer AUTO_INCREMENT,
ID_PRODUCTO integer,
IBAN varchar(255),
PROXIMO_CARGO double,

PRIMARY KEY (ID),
FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS (ID) ON DELETE CASCADE
);

CREATE TABLE COTITULARES(
ID integer AUTO_INCREMENT,
COTITULAR varchar(255),
ID_CUENTA_NOMINA integer,

PRIMARY KEY (ID),
FOREIGN KEY (ID_CUENTA_NOMINA) REFERENCES CUENTAS_NOMINA(ID) ON DELETE CASCADE
);

CREATE TABLE CUENTAS_AHORRO(
ID integer AUTO_INCREMENT,
ID_PRODUCTO integer,
IBAN varchar(255),
TIPO_ACREEDOR double,

PRIMARY KEY (ID),
FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS (ID) ON DELETE CASCADE
);

CREATE TABLE MOVIMIENTOS(
ID integer AUTO_INCREMENT,
CONCEPTO varchar(255),
IMPORTE double,
ID_TARJETA integer,
DIA timestamp DEFAULT CURRENT_TIMESTAMP,

PRIMARY KEY (ID),
FOREIGN KEY (ID_TARJETA) REFERENCES TARJETAS (ID) ON DELETE CASCADE
);