/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import constantes.Mensajes;
import controlador.ControlProductos;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import modelo.productos.Tarjeta;
import utils.Info;

/**
 * Permite mostrar una ventana modal con la información detallada de una tarjeta seleccionada.
 * @author JoséMaría
 */
public class DetalleTarjeta extends javax.swing.JDialog {

    private Tarjeta tarjetaActual;
    private ControlProductos controlProductos;

    /**
     * Crea una nueva ventana modal, con la tarjeta seleccionada en la vista principal. Cuando se crea
     * esta clase, se recoge el parámetro tarjetaActual (la tarjeta seleccionada) y el controlProductos (necesario
     * para llamara a los métodos dao). Ambas instancias ya están creadas en la vista principal y al construirse,
     * se comparten con esta clase.
     */
    public DetalleTarjeta(java.awt.Frame parent, boolean modal, Tarjeta tarjetaActual, ControlProductos controlProductos) {
        super(parent, modal);
        initComponents();
        this.tarjetaActual = tarjetaActual;
        this.controlProductos = controlProductos;
        ((DefaultTableModel) tablaDetalleTarjeta.getModel()).addRow(new Object[]{tarjetaActual.getNumeroTarjeta(),
            tarjetaActual.getTitular(), tarjetaActual.getImporte(), tarjetaActual.getCaducidad(), tarjetaActual.isActivada()});
        if (tarjetaActual.isActivada()) {
            btnActivar.setEnabled(false);
        } else {
            btnDesactivar.setEnabled(false);
        }
        mostrarPanel(panelBotones);
        VistaUtils.getInstance().ponerKeyListenerAlJtf(jtfPIN);
    }

    private void mostrarPanel(JPanel panelVisible) {
        panelBotones.setVisible(false);
        panelPin.setVisible(false);
        panelVisible.setVisible(true);
    }

    private void cambiarBotones() {
        btnActivar.setEnabled(!btnActivar.isEnabled());
        btnDesactivar.setEnabled(!btnDesactivar.isEnabled());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDetalleTarjeta = new javax.swing.JTable();
        panelBotones = new javax.swing.JPanel();
        btnActivar = new javax.swing.JButton();
        btnDesactivar = new javax.swing.JButton();
        panelPin = new javax.swing.JPanel();
        labelPin = new javax.swing.JLabel();
        jtfPIN = new javax.swing.JTextField();
        btnConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaDetalleTarjeta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº TARJETA", "TITULAR", "SALDO DISPUESTO", "CADUCIDAD", "ACTIVADA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaDetalleTarjeta);

        btnActivar.setText("Activar");
        btnActivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivarActionPerformed(evt);
            }
        });
        panelBotones.add(btnActivar);

        btnDesactivar.setText("Desactivar");
        btnDesactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesactivarActionPerformed(evt);
            }
        });
        panelBotones.add(btnDesactivar);

        labelPin.setText("Introduzca nuevo PIN: ");

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPinLayout = new javax.swing.GroupLayout(panelPin);
        panelPin.setLayout(panelPinLayout);
        panelPinLayout.setHorizontalGroup(
            panelPinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPinLayout.createSequentialGroup()
                .addGroup(panelPinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPinLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(labelPin)
                        .addGap(18, 18, 18)
                        .addComponent(jtfPIN, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPinLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(btnConfirmar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPinLayout.setVerticalGroup(
            panelPinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPinLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(panelPinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPin)
                    .addComponent(jtfPIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnConfirmar)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 60, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(panelPin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(133, 133, 133)
                    .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(134, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarActionPerformed
        mostrarPanel(panelPin);

    }//GEN-LAST:event_btnActivarActionPerformed

    private void btnDesactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesactivarActionPerformed
        Info i = controlProductos.desactivarTarjeta(tarjetaActual);
        if (i.isSuccess()) {
            tarjetaActual.setActivada(false);
            ((DefaultTableModel) tablaDetalleTarjeta.getModel()).removeRow(0);
            ((DefaultTableModel) tablaDetalleTarjeta.getModel()).addRow(new Object[]{tarjetaActual.getNumeroTarjeta(), tarjetaActual.getTitular(), tarjetaActual.getImporte(), tarjetaActual.getCaducidad(), tarjetaActual.isActivada()});
            JOptionPane.showMessageDialog(this, i.getMsg(), "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
            cambiarBotones();
        } else {
            JOptionPane.showMessageDialog(this, i.getMsg(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDesactivarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        if (VistaUtils.getInstance().comprobarJtfRellena(jtfPIN)) {
            tarjetaActual.setPIN(jtfPIN.getText());
            Info i = controlProductos.activarTarjeta(tarjetaActual);
            if (i.isSuccess()) {
                tarjetaActual.setActivada(true);
                ((DefaultTableModel) tablaDetalleTarjeta.getModel()).removeRow(0);
                ((DefaultTableModel) tablaDetalleTarjeta.getModel()).addRow(new Object[]{tarjetaActual.getNumeroTarjeta(), tarjetaActual.getTitular(), tarjetaActual.getImporte(), tarjetaActual.getCaducidad(), tarjetaActual.isActivada()});
                mostrarPanel(panelBotones);
                cambiarBotones();
                JOptionPane.showMessageDialog(this, i.getMsg(), "SUCCESS", JOptionPane.INFORMATION_MESSAGE);

            } else {
                JOptionPane.showMessageDialog(this, i.getMsg(), "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, Mensajes.EMPTY_FIELDS, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnDesactivar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtfPIN;
    private javax.swing.JLabel labelPin;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelPin;
    private javax.swing.JTable tablaDetalleTarjeta;
    // End of variables declaration//GEN-END:variables
}
