/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import constantes.Mensajes;
import javax.swing.JOptionPane;
import modelo.personas.Empleado;
import utils.Info;

/**
 * Ventana modal que recoge el formulario para cumplimentar los datos de un nuevo empleado.
 * @author JoséMaría
 */
public class PlantillaNuevoEmpleado extends javax.swing.JDialog {

    private EmpleadoResumenModel model;

    /**
     * Crea una nueva plantilla. Necesita el modelo de la tabla de empleados para realizar
     * la inserción o eliminación y refrescar la tabla.
     */
    public PlantillaNuevoEmpleado(java.awt.Frame parent, boolean modal, EmpleadoResumenModel model) {
        super(parent, modal);
        this.model = model;
        initComponents();
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        VistaUtils.getInstance().ponerKeyListenerAlJtf(jtfDNI);
        VistaUtils.getInstance().ponerKeyListenerAlJtf(jtfNombre);
        VistaUtils.getInstance().ponerKeyListenerAlJtf(jtfApellido1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelDNI = new javax.swing.JLabel();
        labelInfo = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelApellido1 = new javax.swing.JLabel();
        labelApellido2 = new javax.swing.JLabel();
        labelDepartamento = new javax.swing.JLabel();
        jtfDNI = new javax.swing.JTextField();
        jtfNombre = new javax.swing.JTextField();
        jtfApellido1 = new javax.swing.JTextField();
        jtfApellido2 = new javax.swing.JTextField();
        jtfDepartamento = new javax.swing.JTextField();
        checkJefe = new javax.swing.JCheckBox();
        btnConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        labelDNI.setText("DNI:");

        labelInfo.setText("Rellene los siguientes campos:");

        labelNombre.setText("Nombre:");

        labelApellido1.setText("Apellido 1:");

        labelApellido2.setText("Apellido 2:");

        labelDepartamento.setText("Departamento:");

        checkJefe.setText("¿Es Jefe?");

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(labelInfo))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(labelApellido1)
                                .addComponent(labelNombre)
                                .addComponent(labelApellido2)
                                .addComponent(labelDepartamento)
                                .addComponent(checkJefe)
                                .addComponent(labelDNI))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtfNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                .addComponent(jtfApellido1)
                                .addComponent(jtfApellido2)
                                .addComponent(jtfDepartamento)
                                .addComponent(jtfDNI))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(btnConfirmar)))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(labelInfo)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDNI)
                    .addComponent(jtfDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelApellido1)
                    .addComponent(jtfApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelApellido2)
                    .addComponent(jtfApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDepartamento)
                    .addComponent(jtfDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(checkJefe)
                .addGap(27, 27, 27)
                .addComponent(btnConfirmar)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed

        boolean camposRellenos = VistaUtils.getInstance().comprobarJtfRellena(jtfDNI);
        camposRellenos = VistaUtils.getInstance().comprobarJtfRellena(jtfNombre) && camposRellenos;
        camposRellenos = VistaUtils.getInstance().comprobarJtfRellena(jtfApellido1) && camposRellenos;

        if (camposRellenos) {
            Empleado e = new Empleado();
            e.setDni(jtfDNI.getText());
            e.setNombre(jtfNombre.getText());
            e.setApellido1(jtfApellido1.getText());
            e.setApellido2(jtfApellido2.getText());
            e.setDepartamento(jtfDepartamento.getText());
            e.setJefe(checkJefe.isSelected());
            Info info = model.anadirNuevoEmpleado(e);
            if (!info.isSuccess()) {
                JOptionPane.showMessageDialog(this, info.getMsg(), "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, Mensajes.EMPTY_FIELDS, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (JOptionPane.showConfirmDialog(this, "Se perderán todos los cambios. ¿Desea continuar?", "ATENCION", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JCheckBox checkJefe;
    private javax.swing.JTextField jtfApellido1;
    private javax.swing.JTextField jtfApellido2;
    private javax.swing.JTextField jtfDNI;
    private javax.swing.JTextField jtfDepartamento;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JLabel labelApellido1;
    private javax.swing.JLabel labelApellido2;
    private javax.swing.JLabel labelDNI;
    private javax.swing.JLabel labelDepartamento;
    private javax.swing.JLabel labelInfo;
    private javax.swing.JLabel labelNombre;
    // End of variables declaration//GEN-END:variables
}
