/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControlClientes;
import controlador.ControlEmpleados;
import java.util.TreeSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.personas.Cliente;
import utils.Info;

/**
 * Ventana modal que recoge el formulario para cumplimentar los datos de un nuevo cliente.
 * @author JoséMaría
 */
public class PlantillaNuevoCliente extends javax.swing.JDialog {

    private GPLBankEmpleadosGUI parent;
    private ControlClientes controlClientes;
    private ControlEmpleados controlEmpleados;
    private boolean modificar;
    private Cliente clienteActual;
    private ProductosContratadosModel productosContratadosModel;

    /**
     * Crea una nueva plantilla. Necesita: controlClientes(para llamar a los métodos dao de inserción de clientes),
     * controlEmpleados (para llamar a los métodos de clientes captados), un booleano indicando si es para modificar
     * o no, de tal manera que se muestren los campos ya cumplimentados o vacíos, clienteActual (en caso de que
     * modificar sea true) y productosContratadosModel(de tal manera que si se modifican los datos del usuario,
     * se llama al modelo para decirle que refresque el titular en toda la tabla).
     */
    public PlantillaNuevoCliente(java.awt.Frame parent, boolean modal, ControlClientes controlClientes, ControlEmpleados controlEmpleados, boolean modificar, Cliente clienteActual, ProductosContratadosModel productosContratadosModel) {
        super(parent, modal);
        initComponents();
        this.controlClientes = controlClientes;
        this.controlEmpleados = controlEmpleados;
        this.parent = (GPLBankEmpleadosGUI) parent;
        this.modificar = modificar;
        if (modificar) {
            this.clienteActual = clienteActual;
            this.productosContratadosModel = productosContratadosModel;
            rellenarCampos();
        }
        ponerKeyListeners();
    }

    private void rellenarCampos() {
        jLabelTelefono.setVisible(false);
        jtfTelefono.setVisible(false);
        jtfDNI.setText(clienteActual.getDni());
        jtfDNI.setEditable(false);
        jtfDNI.setEnabled(false);
        jtfNombre.setText(clienteActual.getNombre());
        jtfApellido1.setText(clienteActual.getApellido1());
        jtfApellido2.setText(clienteActual.getApellido2());
    }
   
    private void ponerKeyListeners(){
        VistaUtils.getInstance().ponerKeyListenerAlJtf(jtfDNI);
        VistaUtils.getInstance().ponerKeyListenerAlJtf(jtfNombre);
        VistaUtils.getInstance().ponerKeyListenerAlJtf(jtfApellido1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelInfo = new javax.swing.JLabel();
        jLabelDNI = new javax.swing.JLabel();
        jtfDNI = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jLabelApellido1 = new javax.swing.JLabel();
        jtfApellido1 = new javax.swing.JTextField();
        jLabelApellido2 = new javax.swing.JLabel();
        jtfApellido2 = new javax.swing.JTextField();
        jLabelTelefono = new javax.swing.JLabel();
        jtfTelefono = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelInfo.setText("Rellene los siguientes campos:");

        jLabelDNI.setText("DNI:");

        jLabelNombre.setText("Nombre:");

        jLabelApellido1.setText("Apellido 1:");

        jLabelApellido2.setText("Apellido 2:");

        jLabelTelefono.setText("Telefono:");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelDNI)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtfDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabelInfo)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelApellido1)
                                .addComponent(jLabelNombre)
                                .addComponent(jLabelApellido2)
                                .addComponent(jLabelTelefono))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtfNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                                .addComponent(jtfApellido1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jtfApellido2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jtfTelefono, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(btnGuardar)))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabelInfo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDNI)
                    .addComponent(jtfDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelApellido1)
                    .addComponent(jtfApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelApellido2)
                    .addComponent(jtfApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelefono)
                    .addComponent(jtfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        boolean datosRellenos = VistaUtils.getInstance().comprobarJtfRellena(jtfDNI);
        datosRellenos = VistaUtils.getInstance().comprobarJtfRellena(jtfNombre) && datosRellenos;
        datosRellenos = VistaUtils.getInstance().comprobarJtfRellena(jtfApellido1) && datosRellenos;

        if (datosRellenos) {

            String dni = jtfDNI.getText();
            String nombre = jtfNombre.getText();
            String apellido1 = jtfApellido1.getText();
            String apellido2 = jtfApellido2.getText();
            TreeSet<String> telefonos = new TreeSet<>();
            if (!jtfTelefono.getText().equals("")) {
                telefonos.add(jtfTelefono.getText());
            }

            Cliente c = new Cliente(nombre, apellido1, apellido2, dni, "", telefonos);
            if (!modificar) {
                Info info = controlClientes.addCliente(c);
                if (info.isSuccess()) {
                    controlEmpleados.anotarClienteCaptado(parent.getEmpleadoActivo());
                    JOptionPane.showMessageDialog(this, info.getMsg(), "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, info.getMsg(), "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                Info info = controlClientes.modificarCliente(c);
                if (info.isSuccess()) {
                    productosContratadosModel.refresh();
                    clienteActual = c;
                    ((DefaultTableModel) parent.getTablaDatosCliente().getModel()).removeRow(0);
                    ((DefaultTableModel) parent.getTablaDatosCliente().getModel()).addRow(new Object[]{clienteActual.getDni(), clienteActual.getNombre(), clienteActual.getApellido1(), clienteActual.getApellido2()});
                    JOptionPane.showMessageDialog(this, info.getMsg(), "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, info.getMsg(), "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Rellene los campos", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabelApellido1;
    private javax.swing.JLabel jLabelApellido2;
    private javax.swing.JLabel jLabelDNI;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JTextField jtfApellido1;
    private javax.swing.JTextField jtfApellido2;
    private javax.swing.JTextField jtfDNI;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfTelefono;
    // End of variables declaration//GEN-END:variables
}
